notification/urls.py
from django.urls import path

from notification.views import user_notifications, mark_as_read

app_name = 'notification'

urlpatterns = [
    path('', user_notifications, name='user_notifications'),
    path('read/<int:notification_id>/', mark_as_read, name='mark_as_read'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('user-notifications/', include('notification.urls'))
]

users/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view, update_profile, get_profile, toggle_profile_like

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('registration/', register_view, name='registration'),
    path('logout/', logout_view, name='logout'),
    path('profile/', update_profile, name='profile'),
    path('profile/<int:user_id>/', get_profile, name='get_profile'),
    path('profile/<int:profile_id>/like/', toggle_profile_like, name='toggle_profile_like')
]

notification/models.py
from django.db import models
from users.models import CustomUser


class Notification(models.Model):
    recipient = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_notifications')
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sender_notifications')
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Уведомление от {self.sender.username} для {self.recipient.username}: {self.message}"

notification/views.py
from django.shortcuts import render, redirect, get_object_or_404

from notification.models import Notification


def user_notifications(request):
    notification_list = Notification.objects.filter(recipient=request.user)
    return render(request, 'notification/notification_list.html', {'notification_list': notification_list})


def mark_as_read(request, notification_id):
    notification = get_object_or_404(Notification, id=notification_id, recipient=request.user)
    if not notification.is_read:
        notification.is_read = True
        notification.save()
    else:
        notification.is_read = False
        notification.save()
    previous_page = request.META.get('HTTP_REFERER', '/')
    return redirect(previous_page)

templates/notification/notification_list.html
{% extends 'articles/base.html' %}
{% block title %}IPoster | Ваши уведомления{% endblock %}

{% block content %}
    <h2>Уведомления</h2>

    <ul>
        {% for notification in notification_list %}
            <li {% if not notification.is_read %} style="font-weight: bold;" {% endif %}>
                {{ notification.message }} — {{ notification.created_at|date:"d.m.Y H:i" }}
                {% if not notification.is_read %}
                    <a href="{% url 'notification:mark_as_read' notification.id %}">Отметить как прочитанное</a>
                {% else %}
                    <a href="{% url 'notification:mark_as_read' notification.id %}">Убрать пометку прочитанное</a>
                {% endif %}
            </li>
        {% empty %}
            <li>Нет уведомлений.</li>
        {% endfor %}
    </ul>

{% endblock content%}