articles/urls.py
from django.urls import path

from articles.views import home, new_articles, user_articles, delete_article, add_to_favorites, remove_from_favorites, favorite_articles, toggle_article_like

app_name = 'articles'

urlpatterns = [
    path('', home, name='home'),
    path('new-articles/', new_articles, name='new_articles'),
    path('my-articles/', user_articles, name='user_articles'),
    path('delete/<int:article_id>/', delete_article, name='delete_article'),
    path('add_to_favorites/<int:article_id>/', add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:article_id>/', remove_from_favorites, name='remove_from_favorites'),
    path('favorite_articles/', favorite_articles, name='favorite_articles'),
    path('like/<int:article_id>/', toggle_article_like, name='toggle_article_like')
]

notification/urls.py
from django.urls import path

from notification.views import user_notifications, mark_as_read

app_name = 'notification'

urlpatterns = [
    path('', user_notifications, name='user_notifications'),
    path('read/<int:notification_id>/', mark_as_read, name='mark_as_read'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('user-notifications/', include('notification.urls'))
]

users/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view, update_profile, get_profile, toggle_profile_like

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('registration/', register_view, name='registration'),
    path('logout/', logout_view, name='logout'),
    path('profile/', update_profile, name='profile'),
    path('profile/<int:user_id>/', get_profile, name='get_profile'),
    path('profile/<int:profile_id>/like/', toggle_profile_like, name='toggle_profile_like')
]

articles/models.py
from django.db import models
from django.conf import settings


class Articles(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles', blank=True)

    class Meta:
        ordering = ['-date']  # сортировка по дате создания


class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='favorites')
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'article')  # один и тот же пользователь не может добавить одну
                                               # и ту же статью в избранное несколько раз

articles/forms.py
from django import forms
from .models import Articles


class CreateArticleForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ('title', 'text')

articles/views.py
from django.shortcuts import get_object_or_404, render, redirect

from articles.models import Articles, Favorite
from .forms import CreateArticleForm
from notification.models import Notification


def home(request):
    context = {'articles': Articles.objects.all()}

    if request.user.is_authenticated:
        favorite_articles_ids = Favorite.objects.filter(user=request.user).values_list('article_id', flat=True)
        liked_articles = request.user.liked_articles.values_list('id', flat=True)
        context.update({
            'favorite_articles': favorite_articles_ids,
            'liked_articles': liked_articles,
        })

    return render(request, 'articles/home.html', context)


def user_articles(request):
    context = {
        'articles': Articles.objects.filter(author=request.user),
    }

    return render(request, 'articles/user_articles.html', context)


def new_articles(request):
    if request.method == 'POST':
        form = CreateArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            form.save()
            """Сохранение формы: form.save() сохраняет данные формы в базу данных. 
            Это возможно благодаря тому, что форма является моделевой формой (ModelForm), 
            которая знает, как преобразовать данные формы в экземпляр модели"""
            return redirect('articles:home')
    else:
        form = CreateArticleForm()

    return render(request, 'articles/new_articles.html', {'form': form})


def delete_article(request, article_id):
    article = Articles.objects.get(id=article_id, author=request.user)
    article.delete()

    return redirect('articles:user_articles')


def add_to_favorites(request, article_id):
    article = Articles.objects.get(id=article_id)
    Favorite.objects.create(user=request.user, article=article)

    previous_page = request.META.get('HTTP_REFERER', '/')
    return redirect(previous_page)


def remove_from_favorites(request, article_id):
    article = Articles.objects.get(id=article_id)
    Favorite.objects.filter(user=request.user, article=article).delete()

    previous_page = request.META.get('HTTP_REFERER', '/')
    return redirect(previous_page)


def favorite_articles(request):

    favorite_articles_ids = Favorite.objects.filter(user=request.user).values_list('article_id', flat=True)
    articles = Articles.objects.filter(id__in=favorite_articles_ids)

    context = {
        'articles': articles,
    }

    return render(request, 'articles/favorite_articles.html', context)


def toggle_article_like(request, article_id):
    article = get_object_or_404(Articles, id=article_id)
    if request.user in article.likes.all():
        article.likes.remove(request.user)
    else:
        article.likes.add(request.user)

        if article.author != request.user:
            Notification.objects.create(
                recipient=article.author,
                sender=request.user,
                message=f"{request.user.username} лайкнул вашу статью «{article.title}»",
            )

    previous_page = request.META.get('HTTP_REFERER', '/')
    return redirect(previous_page)

templates/articles/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
</head>
<body>
    <div class="sidebar">
        <a href="{% url 'articles:home' %}" class="logo">IPoster</a>
        <div class="menu">
            {% if user.is_authenticated %}
                <a href="{% url 'articles:home' %}">Главная</a>
                <a href="{% url 'users:profile' %}">Профиль</a>
                <a href="{% url 'articles:favorite_articles' %}">Избранное</a>
                <a href="{% url 'articles:user_articles' %}">Мои публикации</a>
                <a href="{% url 'notification:user_notifications' %}">Уведомления</a>
                <a href="{% url 'articles:new_articles' %}" class="create-post-button">Создать новую публикацию</a>
            {% endif %}
        </div>
        <div class="login-button">
            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">Выход</a>
            {% else %}
                <a href="{% url 'users:login' %}">Вход</a>
            {% endif %}
        </div>
    </div>
    <div class="content">
        <div class="content-box">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

templates/articles/favorite_articles.html
{% extends 'articles/base.html' %}
{% block title %}IPoster | Главная страница{% endblock %}

{% block content %}

    <h2>Избранные публикации</h2>

    <div class="articles-feed">
        {% for article in articles %}
            <div class="article">
                <h3>{{ article.title }}</h3>
                <p>{{ article.text }}</p>
                <div class="article-info">
                    <a class="article-author" href="{% url 'users:get_profile' user_id=article.author.id %}">
                            {{ article.author.username }}
                    </a>

                    <span class="likes-count">{{ article.likes.count }} ❤️</span>

                    <form method="post" action="{% url 'articles:toggle_article_like' article_id=article.id %}" style="display:inline;">
                        {% csrf_token %}
                        {% if article.id in liked_articles %}
                            <button type="submit" class="like-button">Убрать лайк</button>
                        {% else %}
                            <button type="submit" class="like-button">Поставить лайк</button>
                        {% endif %}
                    </form>

                    <form method="post" action="{% url 'articles:remove_from_favorites' article.id %}">
                        {% csrf_token %}
                        <button type="submit" class="favorite-button remove-favorite">Удалить из избранного</button>
                    </form>
                    <div class="article-date">{{ article.date|date:"d.m.Y H:i" }}</div>
                </div>
            </div>
        {% empty %}
            <div class="articles-feed empty">
                <div class="empty-state-container">
                    <h1>Добро пожаловать в IPoster!</h1>
                    <p>Здесь будут ваши избранные публикации.</p>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/articles/home.html
{% extends 'articles/base.html' %}
{% block title %}IPoster | Главная страница{% endblock %}

{% block content %}
    <h2>Публикации</h2>
    <div class="articles-feed">
        {% if user.is_authenticated %}
            {% for article in articles %}
                <div class="article">
                    <h3>{{ article.title }}</h3>
                    <p>{{ article.text }}</p>
                    <div class="article-info">
                        <a class="article-author" href="{% url 'users:get_profile' user_id=article.author.id %}">
                            {{ article.author.username }}
                        </a>

                        <span class="likes-count">{{ article.likes.count }} ❤️</span>

                        <form method="post" action="{% url 'articles:toggle_article_like' article_id=article.id %}" style="display:inline;">
                            {% csrf_token %}
                            {% if article.id in liked_articles %}
                                <button type="submit" class="like-button">Убрать лайк</button>
                            {% else %}
                                <button type="submit" class="like-button">Поставить лайк</button>
                            {% endif %}
                        </form>

                        {% if article.id in favorite_articles %}
                            <form method="post" action="{% url 'articles:remove_from_favorites' article_id=article.id %}">
                                {% csrf_token %}
                                <button type="submit" class="favorite-button remove-favorite">Удалить из избранного</button>
                            </form>
                        {% else %}
                            <form method="post" action="{% url 'articles:add_to_favorites' article.id %}">
                                {% csrf_token %}
                                <button type="submit" class="favorite-button add-favorite">Добавить в избранное</button>
                            </form>
                        {% endif %}

                        <span class="article-date">{{ article.date|date:"d.m.Y H:i" }}</span>
                    </div>
                </div>
            {% empty %}
                <div class="articles-feed empty">
                    <div class="empty-state-container">
                        <h1>Добро пожаловать в IPoster!</h1>
                        <p>Здесь будут ваши статьи и публикации.</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="articles-feed empty">
                <div class="empty-state-container">
                    <h1>Добро пожаловать в IPoster!</h1>
                    <p>Здесь будут ваши статьи и публикации.</p>
                    <p>Создайте аккаунт или войдите.</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/articles/new_articles.html
{% extends 'articles/base.html' %}
{% block title %}IPoster | Создание новой публикации {% endblock %}

{% block content %}
    <form method="post" class="article-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Придумай интересное назавание твоей статьи:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="{{ form.text.id_for_label }}">Напиши основной текст:</label>
            {{ form.text }}
        </div>
        <button type="submit" class="create-button">Создать статью</button>
    </form>
{% endblock %}

templates/articles/user_articles.html
{% extends 'articles/base.html' %}
{% block title %}IPoster | Ваши публикации{% endblock %}

{% block content %}
    <h2>Ваши публикации</h2>

    <div class="articles-feed">
        {% for article in articles %}
            <div class="article">
                <h3>{{ article.title }}</h3>
                <p>{{ article.text }}</p>
                <div class="article-info">
                    <div class="article-author">{{ article.author.username }}</div>

                    <span class="likes-count">{{ article.likes.count }} ❤️</span>

                    <form method="post" action="{% url 'articles:delete_article' article.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-button">Удалить</button>
                    </form>

                    <div class="article-date">
                        {{ article.date|date:"d.m.Y H:i" }}
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="articles-feed empty">
                <div class="empty-state-container">
                    <h1>Добро пожаловать в IPoster!</h1>
                    <p>Здесь будут ваши статьи и публикации.</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}